/* SELECIONANDO A TABLE*/
SELECT * 
FROM Person.Person;

/*SELECIONANDO A TABELA E COLUNA ESPECÍFICA*/
SELECT Title
FROM Person.Person;

/**/
SELECT * FROM person.EmailAddress;

/*DESAFIO 01
A EQUIPE DE MARKETING PRECISA FAZER UMA PESQUISA SOBRE OS NOMES
E SOBRENOMES MAIS COMUNS DE SEUS CLIENTES NO SISTEMA
*/
SELECT FirstName, LastName
FROM person.person;

