SELECT * 
FROM Person.Person;

/*VERIFICAR APENAS FIRSTNAME*/
SELECT firstName
FROM Person.Person; /*POSSUI 19.972 LINHAS*/

/*USANDO DISTINCT PARA MOSTRAR REGISTROS SEM ESTAREM DUPLICADOS*/
SELECT DISTINCT firstName
FROM Person.Person; /*POSSUI APENAS 1.018 REGISTROS*/

/*DESAFIO 2
QUANTOS SOBRENOMES ÚNICOS TEMOS NA TABELA PERSON.PERSON?
*/
SELECT DISTINCT lastName
FROM Person.Person; /*1.206 REGISTROS*/