/*
OPERADOR LÓGICO	 -	DESCRIÇÃO
=					IGUAL
>					MAIOR QUE
<					MENOR QUE
>=					MAIOR OU IGUAL QUE
<=					MENOR OU IGUAL QUE
<>					DIFERENTE
AND					OPERADOR LÓGICO E
OR					OPERADOR LÓGICO OU
*/

SELECT *
FROM Person.Person;

-- SELECIONAR SOBRENOMES QUE SEJAM IGUAL A Miller
SELECT *
FROM Person.Person
WHERE LastName = 'Miller'; -- 87 registros

-- SELECIONAR SOBRENOMES QUE SEJAM IGUAL A MILLER E NOME ANNA
SELECT *
FROM Person.Person
WHERE LastName = 'Miller' AND FirstName = 'Anna'; -- 1 REGISTRO

-- VER TABELA PRODUCT
SELECT *
FROM Production.Product; -- 504 REGISTROS

--VERIFICAR PRODUTOS QUE SAO DAS CORES VERMELHA OU AZUIS
SELECT *
FROM Production.Product
WHERE Color = 'Blue' OR Color = 'Black'; -- 119 REGISTROS

-- PRODUTOS QUE ESTAO ACIMA DE 1500 DÓLARES
SELECT *
FROM Production.Product
WHERE ListPrice > 1500; -- 39 REGISTROS

-- PRODUTOS QUE TEM PREÇO MAIOR QUE 1500 E MENOR QUE 5000 DÓLARES
SELECT *
FROM Production.Product
WHERE ListPrice > 1500 AND ListPrice < 5000; -- 39 REGISTROS

-- PRODUTOS QUE NÃO SÃO DA COR VERMELHA
SELECT *
FROM Production.Product
WHERE Color <> 'red'; -- 218 REGISTROS

/*
DESAFIO 01
A EQUIPE DE PRODUÇÃO PRECISA DO NOME DE TODAS AS PEÇAS
QUE PESAM MAIS QUE 500KG, MAS NAO MAIS QUE 700KG PARA INSPEÇÃO
*/
SELECT *
FROM Production.Product
WHERE Weight > 500 AND Weight <= 700; -- 4 REGISTROS

/*
DESAFIO 02
FOI PEDIDO PELO MARKETING UMA RELAÇÃO DE TODOS OS EMPREGADOS(EMPLOYEES)
QUE SÃO CASADOS(SINGLE=SOLTEIRO, MARRIED=CASADO) E SÃO ASSALARIADOS(SALARIED)
*/
SELECT *
FROM HumanResources.Employee
WHERE MaritalStatus = 'M' AND SalariedFlag = '1'; -- 28 REGISTROS

/*
DESAFIO 03
UM USUÁRIO CHAMADO PETER KREBS ESTÁ DEVENDO UM PAGAMENTO, CONSIGA
O E-MAIL DELE PARA QUE POSSAMOS ENVIAR UMA COBRANÇA!
(USAR TABELA PERSON.PERSON E DEPOIS A TABELA
PERSON.EMAILADRESS)
*/
SELECT *
FROM Person.Person
WHERE FirstName = 'Peter' AND LastName = 'Krebs'; -- 1 REGISTRO

SELECT *
FROM Person.EmailAddress
WHERE BusinessEntityID = 26;
