-- COUNT - PARA VERIFICAR QUANTIDADE DE REGISTROS NA TABELA
SELECT *
FROM Person.Person; -- 19972 REGISTROS

SELECT COUNT(*)
FROM Person.Person; -- 19972

SELECT COUNT(Title)
FROM Person.Person; -- 1009 REGISTROS

SELECT COUNT(DISTINCT Title)
FROM Person.Person; -- 6 REGISTROS NAO DUPLICADOS

/*
 * DESAFIO 01
 * EU QUERO SABER QUANTOS PRODUTOS TEMOS CADASTRADOS EM NOSSA TABELA DE PRODUTOS
 */
SELECT COUNT(*)
FROM Production.Product; -- 504 REGISTROS

/*
 * DESAFIO 02
 * EU QUERO SABER QUANTOS TAMANHOS DE PRODUTOS TEMOS CADASTRADOS EM NOSSA TABELA
 */
SELECT *
FROM Production.Product;

SELECT COUNT(Size)
FROM Production.Product; -- 211 REGISTROS

/*
 * DESAFIO 03
 * EU QUERO SABER QUANTOS TAMANHOS DIFERENTES DE PRODUTOS EU TENHO CADASTRADO NA TABELA
 */
SELECT COUNT(DISTINCT Size)
FROM Production.Product; -- 18 REGISTROS








